name: MacOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: make
      run: |
        brew install boost htslib cmake
        export CXXFLAGS="-I$(brew --prefix boost)/include -I$(brew --prefix htslib)/include"
        export LDFLAGS="-L$(brew --prefix boost)/lib -L$(brew --prefix htslib)/lib"
        make
